project_id = "ugjeubqwmgnqvohmrkyv"

[functions.generate-blog-seo]
verify_jwt = false

[functions.enhance-workflow-seo]
verify_jwt = false

[functions.sync-workflows]
verify_jwt = false

[functions.generate-workflow-descriptions]
verify_jwt = false

[functions.verify-workflow-descriptions]
verify_jwt = false

[functions.generate-embeddings]
verify_jwt = false

[functions.semantic-search]
verify_jwt = false

[functions.send-contact-notification]
verify_jwt = false

[functions.send-booking-notification]
verify_jwt = false

[functions.get-calendly-availability]
verify_jwt = false

[functions.create-calendly-booking]
verify_jwt = false

[functions.send-lead-verification]
verify_jwt = false

[functions.increment-download-count]
verify_jwt = false

[functions.verify-lead-email]
verify_jwt = false