project_id = "ugjeubqwmgnqvohmrkyv"

[functions.sync-workflows]
verify_jwt = false

[functions.generate-workflow-descriptions]
verify_jwt = false

[functions.verify-workflow-descriptions]
verify_jwt = false

[functions.generate-embeddings]
verify_jwt = false

[functions.semantic-search]
verify_jwt = false

[functions.send-contact-notification]
verify_jwt = false

[functions.send-booking-notification]
verify_jwt = false